# 1.4.4 Smoothing Images

## Kernel Convolution

In [18]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [19]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [20]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [21]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [22]:
img

array([[5, 5, 4, 4, 2, 5, 9, 7, 6, 3, 0, 3],
       [4, 5, 6, 9, 6, 8, 0, 2, 4, 1, 9, 1],
       [3, 4, 2, 5, 3, 7, 8, 6, 2, 3, 9, 6],
       [9, 7, 1, 3, 1, 0, 0, 7, 1, 6, 4, 2],
       [7, 9, 4, 6, 5, 0, 5, 6, 5, 3, 9, 1],
       [0, 3, 6, 2, 5, 6, 4, 0, 0, 8, 1, 1],
       [2, 3, 4, 9, 1, 9, 9, 2, 0, 3, 3, 5],
       [3, 4, 4, 9, 2, 9, 5, 1, 6, 0, 5, 4],
       [3, 6, 9, 8, 4, 6, 1, 3, 9, 9, 2, 9],
       [9, 8, 3, 4, 9, 2, 0, 1, 9, 3, 5, 3],
       [2, 5, 7, 0, 8, 5, 0, 6, 5, 3, 3, 7],
       [2, 7, 3, 8, 5, 5, 3, 5, 2, 3, 5, 2]])

In [23]:
h,w=img.shape

In [24]:
print(h,w)

12 12


In [25]:
#[*range(-2,3)]

In [26]:
dst = np.zeros((h,w),np.int)

<ipython-input-26-6137fcb8b1c2>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [27]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [28]:
img

array([[5, 5, 4, 4, 2, 5, 9, 7, 6, 3, 0, 3],
       [4, 5, 6, 9, 6, 8, 0, 2, 4, 1, 9, 1],
       [3, 4, 2, 5, 3, 7, 8, 6, 2, 3, 9, 6],
       [9, 7, 1, 3, 1, 0, 0, 7, 1, 6, 4, 2],
       [7, 9, 4, 6, 5, 0, 5, 6, 5, 3, 9, 1],
       [0, 3, 6, 2, 5, 6, 4, 0, 0, 8, 1, 1],
       [2, 3, 4, 9, 1, 9, 9, 2, 0, 3, 3, 5],
       [3, 4, 4, 9, 2, 9, 5, 1, 6, 0, 5, 4],
       [3, 6, 9, 8, 4, 6, 1, 3, 9, 9, 2, 9],
       [9, 8, 3, 4, 9, 2, 0, 1, 9, 3, 5, 3],
       [2, 5, 7, 0, 8, 5, 0, 6, 5, 3, 3, 7],
       [2, 7, 3, 8, 5, 5, 3, 5, 2, 3, 5, 2]])

In [29]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   4,  15,   2,  14, -27,  -9,   5, -15,  25,   0],
       [  0,  -1,  -8,   3,  -7,   9,  19,   5,  -6,  -6,  14,   0],
       [  0,   5, -12,  -1,  -7,  -8, -20,  15, -16,  13, -10,   0],
       [  0,  15,  -6,  10,   8, -16,  10,   7,  10, -16,  27,   0],
       [  0,  -6,  11, -18,   6,   6,  -4, -12, -13,  25, -17,   0],
       [  0,  -1,  -6,  20, -21,  11,  16,  -2, -11,   1,  -2,   0],
       [  0,   0, -10,  13, -15,  14,   0, -12,  14, -23,  11,   0],
       [  0,   0,  15,   6,  -9,   8, -10,   0,   9,  22, -20,   0],
       [  0,   9, -16,  -4,  18, -12,  -4, -14,  18, -14,   9,   0],
       [  0,  -4,  17, -27,  13,   5, -14,  13,   0,  -2,  -8,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [30]:
img = cv2.imread('lena.png', 0)

In [31]:
h,w=img.shape

In [35]:
l=1
kernel = np.array([[0,-1,0],[-1,5,-1],[0,-1,0]],np.float32)

In [36]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [37]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [38]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()